DATA:
  data_root: dataset/ILSVRC2012
  data_name: imagenet
  classes: 1000

TRAIN:
  arch: san
  sa_type: 1
  layers: [3, 3, 4, 6, 3]
  kernels: [3, 7, 7, 7, 7]
  ignore_label: 2000
  train_gpu: [0, 1, 2, 3, 4, 5, 6, 7]
  workers: 32  # data loader workers
  batch_size: 256  # batch size for training
  batch_size_val: 128  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.1
  epochs: 100
  start_epoch: 0
  step_epochs: [30, 60, 90]
  label_smoothing: 0.1
  mixup_alpha:
  scheduler: cosine
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/imagenet/san19_patchwise/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_gpu: [0]
  test_workers: 10
  batch_size_test: 100
  model_path: exp/imagenet/san19_patchwise/model/model_best.pth